version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
  - package-ecosystem: gradle
    directory: "/"
    schedule:
      interval: daily
      time: "23:00"
    open-pull-requests-limit: 10
