version: '{build}'

environment:
  matrix:
    - job_name: Java 8
      JAVA_HOME: C:\Program Files\Java\jdk1.8.0
      PYTHON: "C:\\Python36-x64"
    - job_name: Java 11
      JAVA_HOME: C:\Program Files\Java\jdk11
      PYTHON: "C:\\Python36-x64"
#        - job_name: Java 16
#          appveyor_build_worker_image: Visual Studio 2019
#          JAVA_HOME: C:\Program Files\Java\jdk16
#          PYTHON: "C:\\Python36-x64"

install:
  - set PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%
  - pip install codecov --user

build_script:
  - ./gradlew assemble --no-daemon
test_script:
  - ./gradlew check --no-daemon

on_success:
  - ./gradlew jacocoTestReport --no-daemon
  - python -m codecov -f build\reports\jacoco\test\jacocoTestReport.xml -F windows

cache:
  - C:\Users\appveyor\.gradle\caches
  - C:\Users\appveyor\.gradle\wrapper