version: '{build}'

environment:
  matrix:
    - job_name: Java 8
      JAVA_HOME: C:\Program Files\Java\jdk1.8.0
    - job_name: Java 11
      JAVA_HOME: C:\Program Files\Java\jdk11
#        - job_name: Java 16
#          appveyor_build_worker_image: Visual Studio 2019
#          JAVA_HOME: C:\Program Files\Java\jdk16

build_script:
  - ./gradlew assemble --no-daemon
test_script:
  - ./gradlew check --no-daemon

on_success:
  - ./gradlew jacocoTestReport --no-daemon
  - ps: |
      $ProgressPreference = 'SilentlyContinue'
      Invoke-WebRequest -Uri https://uploader.codecov.io/latest/windows/codecov.exe -Outfile codecov.exe
      .\codecov.exe -f build\reports\jacoco\test\jacocoTestReport.xml -F windows

cache:
  - C:\Users\appveyor\.gradle\caches
  - C:\Users\appveyor\.gradle\wrapper